- name: Ruby | Checking installed version
  shell: ruby -v | grep -o "ruby {{ ruby_version }}"
  register: _installed
  ignore_errors: True

- name: Ruby | Download
  get_url: "url={{ ruby_url }} dest={{ ruby_tmp_path }}.tar"
  when: _installed.rc == 1 

- name: Ruby | Extract
  command: tar -zxf "{{ ruby_tmp_path }}.tar"
  when: _installed.rc == 1
- name: Make, configure, and install ruby
  command: "{{ item }} chdir={{ ruby_name }}"
  with_items:
    - ./configure
    - make
    - sudo make install
  when: _installed.rc == 1
    
- name: Ruby | Install bundler
  command: sudo gem install {{ item.name }}
  with_items:
   - { name: 'bundler'}

- name: Ruby | Update permissions  
  command: "sudo chown -R {{ deploy_user }} /usr/local/lib/ruby"
  when: deploy_user is defined